baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "workshop-materials"
defaultContentLanguage = "en"

[params]
  subject = "IT"
  feedbackLink = "https://github.com/experimental-software/workshop-materials/issues/new"
